/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */
import * as web3 from '@solana/web3.js';
import * as beet from '@metaplex-foundation/beet';
export declare type EventHost = {
    eventsCreated: web3.PublicKey[];
    displayName: string;
    pubKey: web3.PublicKey;
    profileImage: string;
    eventCount: beet.bignum;
    bump: number;
};
/**
 * @category userTypes
 * @category generated
 */
export declare const eventHostBeet: beet.FixableBeetArgsStruct<EventHost>;
