/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */
import * as web3 from '@solana/web3.js';
/**
 * @category Instructions
 * @category InitializeAdmin
 * @category generated
 */
export declare type InitializeAdminInstructionArgs = {
    admins: web3.PublicKey[];
};
/**
 * Accounts required by the _initializeAdmin_ instruction
 * @category Instructions
 * @category InitializeAdmin
 * @category generated
 */
export declare type InitializeAdminInstructionAccounts = {
    adminAccount: web3.PublicKey;
    adminAuthority: web3.PublicKey;
};
/**
 * Creates a _InitializeAdmin_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category InitializeAdmin
 * @category generated
 */
export declare function createInitializeAdminInstruction(accounts: InitializeAdminInstructionAccounts, args: InitializeAdminInstructionArgs): web3.TransactionInstruction;
