/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */
import * as beet from '@metaplex-foundation/beet';
import * as web3 from '@solana/web3.js';
/**
 * @category Instructions
 * @category MintTicket
 * @category generated
 */
export declare type MintTicketInstructionArgs = {
    uri: string;
};
/**
 * @category Instructions
 * @category MintTicket
 * @category generated
 */
export declare const mintTicketStruct: beet.FixableBeetArgsStruct<MintTicketInstructionArgs & {
    instructionDiscriminator: number[];
}>;
/**
 * Accounts required by the _mintTicket_ instruction
 *
 * @property [_writable_, **signer**] mintAuthority
 * @property [_writable_] eventAccount
 * @property [_writable_, **signer**] mint
 * @property [_writable_] metadata
 * @property [_writable_] tokenAccount
 * @property [] tokenMetadataProgram
 * @property [_writable_] payer
 * @property [_writable_] masterEdition
 * @property [_writable_] eventHost
 * @property [_writable_] eventHostKey
 * @property [_writable_] adminAccount
 * @property [_writable_] adminKey
 * @property [_writable_] customSplToken
 * @property [] customSplTokenProgram
 * @property [_writable_] senderCustomSplTokenAta
 * @property [_writable_] hostCustomSplTokenAta
 * @property [_writable_] adminCustomTokenAta
 * @property [] associatedTokenProgram
 * @category Instructions
 * @category MintTicket
 * @category generated
 */
export declare type MintTicketInstructionAccounts = {
    mintAuthority: web3.PublicKey;
    eventAccount: web3.PublicKey;
    mint: web3.PublicKey;
    metadata: web3.PublicKey;
    tokenAccount: web3.PublicKey;
    tokenMetadataProgram: web3.PublicKey;
    payer: web3.PublicKey;
    masterEdition: web3.PublicKey;
    eventHost: web3.PublicKey;
    eventHostKey: web3.PublicKey;
    adminAccount: web3.PublicKey;
    adminKey: web3.PublicKey;
    customSplToken: web3.PublicKey;
    customSplTokenProgram: web3.PublicKey;
    senderCustomSplTokenAta: web3.PublicKey;
    hostCustomSplTokenAta: web3.PublicKey;
    adminCustomTokenAta: web3.PublicKey;
    associatedTokenProgram: web3.PublicKey;
};
export declare const mintTicketInstructionDiscriminator: number[];
/**
 * Creates a _MintTicket_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category MintTicket
 * @category generated
 */
export declare function createMintTicketInstruction(accounts: MintTicketInstructionAccounts, args: MintTicketInstructionArgs): web3.TransactionInstruction;
