/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category InitializeHost
 * @category generated
 */
export type InitializeHostInstructionArgs = {
  displayName: string;
  profileImg: string;
};
/**
 * @category Instructions
 * @category InitializeHost
 * @category generated
 */
export const initializeHostStruct = new beet.FixableBeetArgsStruct<
  InitializeHostInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */;
  }
>(
  [
    ["instructionDiscriminator", beet.uniformFixedSizeArray(beet.u8, 8)],
    ["displayName", beet.utf8String],
    ["profileImg", beet.utf8String],
  ],
  "InitializeHostInstructionArgs"
);
/**
 * Accounts required by the _initializeHost_ instruction
 *
 * @property [_writable_] eventHostAccount
 * @property [_writable_, **signer**] authority
 * @category Instructions
 * @category InitializeHost
 * @category generated
 */
export type InitializeHostInstructionAccounts = {
  eventHostAccount: web3.PublicKey;
  authority: web3.PublicKey;
  systemProgram?: web3.PublicKey;
};

export const initializeHostInstructionDiscriminator = [
  144, 209, 228, 75, 220, 241, 73, 77,
];

/**
 * Creates a _InitializeHost_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category InitializeHost
 * @category generated
 */
export function createInitializeHostInstruction(
  accounts: InitializeHostInstructionAccounts,
  args: InitializeHostInstructionArgs,
  programId = new web3.PublicKey("H8DZgtTkHL9nNjG8zvgqRMxkjXiWtde4nYScsUdzFaDN")
) {
  const [data] = initializeHostStruct.serialize({
    instructionDiscriminator: initializeHostInstructionDiscriminator,
    ...args,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.eventHostAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.authority,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
