/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'

/**
 * @category Instructions
 * @category InitializeAdmin
 * @category generated
 */
export type InitializeAdminInstructionArgs = {
  admins: web3.PublicKey[]
}
/**
 * @category Instructions
 * @category InitializeAdmin
 * @category generated
 */
const initializeAdminStruct = new beet.FixableBeetArgsStruct<
  InitializeAdminInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['admins', beet.array(beetSolana.publicKey)],
  ],
  'InitializeAdminInstructionArgs'
)
/**
 * Accounts required by the _initializeAdmin_ instruction
 * @category Instructions
 * @category InitializeAdmin
 * @category generated
 */
export type InitializeAdminInstructionAccounts = {
  adminAccount: web3.PublicKey
  adminAuthority: web3.PublicKey
}

const initializeAdminInstructionDiscriminator = [
  35, 176, 8, 143, 42, 160, 61, 158,
]

/**
 * Creates a _InitializeAdmin_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category InitializeAdmin
 * @category generated
 */
export function createInitializeAdminInstruction(
  accounts: InitializeAdminInstructionAccounts,
  args: InitializeAdminInstructionArgs
) {
  const { adminAccount, adminAuthority } = accounts

  const [data] = initializeAdminStruct.serialize({
    instructionDiscriminator: initializeAdminInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: adminAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: adminAuthority,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId: new web3.PublicKey(
      'Crvo7H5Qupi7pD63wyyXfoPbzAkU9Hbqwno7xTrXLbKo'
    ),
    keys,
    data,
  })
  return ix
}
