/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from "@solana/spl-token";
import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category MintTicket
 * @category generated
 */
export type MintTicketInstructionArgs = {
  uri: string;
};
/**
 * @category Instructions
 * @category MintTicket
 * @category generated
 */
export const mintTicketStruct = new beet.FixableBeetArgsStruct<
  MintTicketInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */;
  }
>(
  [
    ["instructionDiscriminator", beet.uniformFixedSizeArray(beet.u8, 8)],
    ["uri", beet.utf8String],
  ],
  "MintTicketInstructionArgs"
);
/**
 * Accounts required by the _mintTicket_ instruction
 *
 * @property [_writable_, **signer**] mintAuthority
 * @property [_writable_] eventAccount
 * @property [_writable_, **signer**] mint
 * @property [_writable_] metadata
 * @property [_writable_] tokenAccount
 * @property [] tokenMetadataProgram
 * @property [_writable_] payer
 * @property [_writable_] masterEdition
 * @property [_writable_] eventHost
 * @property [_writable_] eventHostKey
 * @property [_writable_] adminAccount
 * @property [_writable_] adminKey
 * @property [_writable_] customSplToken
 * @property [] customSplTokenProgram
 * @property [_writable_] senderCustomSplTokenAta
 * @property [_writable_] hostCustomSplTokenAta
 * @property [_writable_] adminCustomTokenAta
 * @property [] associatedTokenProgram
 * @category Instructions
 * @category MintTicket
 * @category generated
 */
export type MintTicketInstructionAccounts = {
  mintAuthority: web3.PublicKey;
  eventAccount: web3.PublicKey;
  mint: web3.PublicKey;
  tokenProgram?: web3.PublicKey;
  metadata: web3.PublicKey;
  tokenAccount: web3.PublicKey;
  tokenMetadataProgram: web3.PublicKey;
  payer: web3.PublicKey;
  systemProgram?: web3.PublicKey;
  rent?: web3.PublicKey;
  masterEdition: web3.PublicKey;
  eventHost: web3.PublicKey;
  eventHostKey: web3.PublicKey;
  adminAccount: web3.PublicKey;
  adminKey: web3.PublicKey;
  customSplToken: web3.PublicKey;
  customSplTokenProgram: web3.PublicKey;
  senderCustomSplTokenAta: web3.PublicKey;
  hostCustomSplTokenAta: web3.PublicKey;
  adminCustomTokenAta: web3.PublicKey;
  associatedTokenProgram: web3.PublicKey;
};

export const mintTicketInstructionDiscriminator = [
  159, 167, 223, 60, 138, 6, 23, 29,
];

/**
 * Creates a _MintTicket_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category MintTicket
 * @category generated
 */
export function createMintTicketInstruction(
  accounts: MintTicketInstructionAccounts,
  args: MintTicketInstructionArgs,
  programId = new web3.PublicKey("H8DZgtTkHL9nNjG8zvgqRMxkjXiWtde4nYScsUdzFaDN")
) {
  const [data] = mintTicketStruct.serialize({
    instructionDiscriminator: mintTicketInstructionDiscriminator,
    ...args,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.mintAuthority,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.eventAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.mint,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.metadata,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenMetadataProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.masterEdition,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.eventHost,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.eventHostKey,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.adminAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.adminKey,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.customSplToken,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.customSplTokenProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.senderCustomSplTokenAta,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.hostCustomSplTokenAta,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.adminCustomTokenAta,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.associatedTokenProgram,
      isWritable: false,
      isSigner: false,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
