/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category MintTicket
 * @category generated
 */
const mintTicketStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'MintTicketInstructionArgs'
)
/**
 * Accounts required by the _mintTicket_ instruction
 * @category Instructions
 * @category MintTicket
 * @category generated
 */
export type MintTicketInstructionAccounts = {
  mintAuthority: web3.PublicKey
  eventAccount: web3.PublicKey
  mint: web3.PublicKey
  metadata: web3.PublicKey
  tokenAccount: web3.PublicKey
  tokenMetadataProgram: web3.PublicKey
  payer: web3.PublicKey
  masterEdition: web3.PublicKey
  eventHost: web3.PublicKey
  adminAccount: web3.PublicKey
}

const mintTicketInstructionDiscriminator = [159, 167, 223, 60, 138, 6, 23, 29]

/**
 * Creates a _MintTicket_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 *
 * @category Instructions
 * @category MintTicket
 * @category generated
 */
export function createMintTicketInstruction(
  accounts: MintTicketInstructionAccounts
) {
  const {
    mintAuthority,
    eventAccount,
    mint,
    metadata,
    tokenAccount,
    tokenMetadataProgram,
    payer,
    masterEdition,
    eventHost,
    adminAccount,
  } = accounts

  const [data] = mintTicketStruct.serialize({
    instructionDiscriminator: mintTicketInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: mintAuthority,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: eventAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: mint,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: metadata,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: tokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: tokenMetadataProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: payer,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: masterEdition,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: eventHost,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: adminAccount,
      isWritable: true,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId: new web3.PublicKey(
      'Crvo7H5Qupi7pD63wyyXfoPbzAkU9Hbqwno7xTrXLbKo'
    ),
    keys,
    data,
  })
  return ix
}
